-- PUBLIC.TBL_MOVIES definition

-- Drop table

-- DROP TABLE PUBLIC.TBL_MOVIES;

CREATE TABLE PUBLIC.TBL_MOVIES (
	ID BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_B0DFEAAE_CA05_4F78_809A_DAC182837E6C") NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
	GENERA VARCHAR(100),
	RELEASE_DATE DATE,
	CONSTRAINT TBL_MOVIES_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_4 ON PUBLIC.TBL_MOVIES (ID);